[enb]
enb_id = 0x19B
mcc = 001
mnc = 01
mme_addr = 127.0.1.100
gtp_bind_addr = 127.0.1.1
s1c_bind_addr = 127.0.1.1
s1c_bind_port = 0
n_prb = 25
tm = 1
nof_ports = 1

[enb_files]
sib_config = /home/wcc/mp_demo/SDR-APP/srsRAN_4G/antsdr_demo/sib_25prb.conf
rr_config = /home/wcc/mp_demo/SDR-APP/srsRAN_4G/srsenb/rr.conf.example
rb_config = /home/wcc/mp_demo/SDR-APP/srsRAN_4G/srsenb/rb.conf.example

[rf]
dl_earfcn = 2900
tx_gain = 89
rx_gain = 40
device_name = UHD
device_args = type=ant,addr=192.168.1.10,product=E200,recv_frame_size=1472,recv_buff_size=33554432,rx_subdev_spec=A:A,tx_subdev_spec=A:A,send_frame_size=1472,send_buff_size=33554432,num_recv_frames=2048,num_send_frames=2048,ignore_tx_timestamps=false,master_clock_rate=23.04e6,sampling_rate=5.76e6
time_adv_nsamples = 0

[pcap]
enable = false
filename = /tmp/antsdr_enb_mac.pcap
s1ap_enable = false
s1ap_filename = /tmp/antsdr_enb_s1ap.pcap

[log]
all_level = info
all_hex_limit = 32
filename = /tmp/antsdr_enb.log
file_max_size = -1

[gui]
enable = false
